# _0708_2025_sweep_grid.yaml
# parameter sweep using cifar10_myakorn_classification.py
grid:
  n:        [2]
  ch:       [128]
  L:        [3]
  T:        [3,7,15,31,63,127]
  gamma:    [0.01, 0.1, 1.0]
  J_bias:   [false]
  global_omg: [false]
